# Starter pipeline
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'sim007/staticws'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildNumber)'


pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Build done!
  displayName: 'Run a one-line script'