# Starter pipeline
trigger: 'master'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'sim007/staticws'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'Latest'