apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws-deployment
  labels:
    app: staticws  
spec:
  selector:
    matchLabels:
      app: staticws
  replicas: 4
  template:
    metadata:
      labels:
        app: staticws
    spec:
      containers:
      - name: staticws
        image: sim007/staticws:2022
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        #imagePullPolicy: Always
        ports:
        -  containerPort: 80 
---
kind: Service
apiVersion: v1
metadata:
  name: staticws-service
spec:
  selector:
    app: staticws
  ports:
  - protocol: TCP
    port: 4223
    targetPort: 80
  type: LoadBalancer 