apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws-deployment
  labels:
    app: staticws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staticws
  template:
    metadata:
      labels:
        app: staticws
    spec:
      containers:
      - name: staticws
        image: sim007/staticws
        ports:
        - containerPort: 80
---             
apiVersion: v1       
kind: Service
metadata:
  name: staticws
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: staticws