apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws-deployment
  labels:
    app: staticws  
spec:
  selector:
    matchLabels:
      app: staticws
  replicas: 10
  template:
    metadata:
      labels:
        app: staticws
    spec:
      containers:
      - name: staticws
        image: sim007/staticws:2022
        #imagePullPolicy: Always
        ports:
        -  containerPort: 80 
---
kind: Service
apiVersion: v1
metadata:
  name: staticws-service
spec:
  selector:
    app: staticws
  ports:
  - protocol: TCP
    port: 4223
    targetPort: 80
  type: LoadBalancer 