apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws
  labels:
    app: staticws
spec:
  replicas: 4
  selector:
    matchLabels:
      app: staticws
  template:
    metadata:
      labels:
        app: staticws
    spec:
      containers:
      - name: staticws
        image: sim007/staticws:2022
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        #imagePullPolicy: Always
        ports:
        -  containerPort: 80 
---             
apiVersion: v1       
kind: Service
metadata:
  name: staticws-public
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: staticws