apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticws
  labels:
    app: staticws
spec:
  replicas: 10
  selector:
    matchLabels:
      app: staticws
  template:
    metadata:
      labels:
        app: staticws
    spec:
      containers:
      - name: staticws
        image: sim007/staticws:latest
        #command: [/usr/share/nginx/html/start.sh]
        ports:
        - containerPort: 80
        # imagePullPolicy: Always 
---             
apiVersion: v1       
kind: Service
metadata:
  name: staticws
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: staticws